version: '3.3'

services:
  domoticz:
    #nom image
    image: domoticz/avril2022
    #nom conteneur
    container_name: domoticz
    restart: unless-stopped
    # Pass devices to container
    #devices:
    # cle zwave
    #- "/dev/ttyUSB1:/dev/ttyUSB1"
    ports:
      - "8086:8080"
    volumes:
      - ./config:/opt/domoticz/userdata
      #- ./scripts:/opt/domoticz/scripts
      - ./www/modules_lua:/opt/domoticz/www/modules_lua
      - ./log:/home/michel
      #- ./www:/opt/domoticz/www
    environment:
      - TZ=Europe/Paris
      - LOG_PATH=/opt/domoticz/userdata/domoticz.log
      - WEBROOT=domoticz
